# Generated by Django 6.0.4 on 2026-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('icono_class', models.CharField(blank=True, help_text="Clase para FontAwesome/Devicon (ej: 'devicon-django-plain', 'fa-brands fa-python')", max_length=100)),
                ('categoria', models.CharField(choices=[('BACK', 'Backend'), ('FRONT', 'Frontend'), ('DB', 'Base de Datos'), ('TOOLS', 'DevOps & Herramientas'), ('OTHER', 'Otros')], default='BACK', max_length=10)),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='educacion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Educación'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencias Laborales'},
        ),
        migrations.AlterModelOptions(
            name='mensajecontacto',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil Personal', 'verbose_name_plural': 'Perfil Personal'},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['orden', '-fecha_creacion'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tecnologias_skills',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='educacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Detalles relevantes, promedio, cursos aprobados o tesis'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej: Tucumán, Argentina / Remoto', max_length=150),
        ),
        migrations.AddField(
            model_name='mensajecontacto',
            name='leido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar para fijar en los primeros lugares de la home'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen_portada',
            field=models.ImageField(default='', upload_to='proyectos/portadas/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='link_video_demo',
            field=models.URLField(blank=True, null=True, verbose_name='Video Demo / Loom / YouTube'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = primero)'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se autogenera si se deja vacío', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='educacion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar en blanco si continúa en curso', null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='descripcion',
            field=models.TextField(help_text='Logros clave, responsabilidades y stack utilizado'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar en blanco si continúa en curso', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio_corta',
            field=models.TextField(help_text='1 o 2 oraciones de impacto para el hero section.', verbose_name='Introducción / Headline'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='bio_larga',
            field=models.TextField(verbose_name='Acerca de mí'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='especializacion',
            field=models.TextField(blank=True, help_text='Áreas de foco o propuesta de valor técnica.'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(help_text='Ej: Ingeniero en Sistemas de Información | Full Stack Developer', max_length=120),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Formato internacional, ej: +549381XXXXXXX', max_length=30),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(help_text='Detalle del problema, solución técnica y arquitectura implementada'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link_deploy',
            field=models.URLField(blank=True, null=True, verbose_name='Demo en vivo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link_github',
            field=models.URLField(blank=True, null=True, verbose_name='Repositorio GitHub'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='subtitulo',
            field=models.CharField(help_text='Resumen conciso del objetivo o alcance del sistema', max_length=250),
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='experiencias', to='core.tecnologia'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tecnologias_destacadas',
            field=models.ManyToManyField(blank=True, related_name='perfiles', to='core.tecnologia'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(related_name='proyectos', to='core.tecnologia'),
        ),
    ]
